### ISSUE TITLE
JS Exception Line 27. TypeError: undefined is not an object (evaluating 'request.length')

### ISSUE THREAD

**Issue by dustingraves** [AndrianBdn/Paw-NodeHttpCodeGenerator#2]
`Node -v` -> `v5.7.1`
`npm --version` -> `3.6.0`

Paw Extension Log: 

```
Event Loaded extension io.andrian.PawExtensions.NodeHttpCodeGenerator
Event Loaded extension io.andrian.PawExtensions.NodeHttpCodeGenerator
JS Exception Line 27. TypeError: undefined is not an object (evaluating 'request.length')
JS Exception Line 27. TypeError: undefined is not an object (evaluating 'request.length')
```

Install seems fine: 

```
make install
mkdir -p "/Users/<userdir>/Library/Containers/com.luckymarmot.Paw/Data/Library/Application Support/com.luckymarmot.Paw/Extensions/io.andrian.PawExtensions.NodeHttpCodeGenerator/"
cp README.md NodeHttpCodeGenerator.js LICENSE "/Users/<userdir>/Library/Containers/com.luckymarmot.Paw/Data/Library/Application Support/com.luckymarmot.Paw/Extensions/io.andrian.PawExtensions.NodeHttpCodeGenerator/"
```

**Comment by dustingraves** [comment]
Reverting to commit `055cd4525502f49cd7b61968a47a4da17fb664e6` (Single requests) makes the extension work.

**Comment by AndrianBdn** [comment]
@dustingraves Thanks for the info. Are you using new enough version of Paw  (>2.3.2) ?
I've added working with multiple requests by feature request from #1

**Comment by dustingraves** [comment]
I was on 2.2.9, after updating this works.

**Comment by hpogosyan** [comment]
How can I get this to work on 2.3.1?

**Comment by AndrianBdn** [comment]
@hpogosyan here is the commit that brakes compatibility with older versions https://github.com/AndrianBdn/Paw-NodeHttpCodeGenerator/commit/1288deae457dfb9b9c99d9832d418a45819c6577

Are there any problems with newer one? You can just update.

**Comment by hpogosyan** [comment]
@andrianbdn it's the only build that doesn't crash on my Mac. How can I get a built version of your plugin? Make doesn't generate a JS file.

**Comment by AndrianBdn** [comment]
@hpogosyan  I just released new version with a quick compatibility fix. Wasn't able to test it. Feel free to share if it works.

**Comment by hpogosyan** [comment]
@AndrianBdn getting this error in terminal when doing "make install"

`npm WARN paw-node-http-code-generator@0.0.0 No repository field.
tsc
make: tsc: No such file or directory
make: *** [NodeHttpCodeGenerator.js] Error 1`

**Comment by hpogosyan** [comment]
@AndrianBdn it worked! Thanks.
